version: "3.7"
services:
  discovery:
    image: pinal/service-discovery:latest
    container_name: service-discovery
    build:
      context: ./microservice-eureka
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
  gateway:
    image: pinal/service-gateway:latest
    container_name: service-gateway
    build:
      context: ./microservice-zull-gateway
      dockerfile: Dockerfile
    ports:
      - "8762:8762"
    depends_on:
      - discovery
    links:
      - "discovery" 