server:
  port: ${PORT:8762}

spring:
  application:
    name: microservice-zull-gateway

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:      defaultZone: http://discovery:8761/eureka/